name: Node setup
author: trunk.io
description: The official trunk.io GitHub action

branding:
  icon: check
  color: orange

runs:
  using: composite
  steps:
    - name: Detect npm/yarn/pnpm
      id: detect
      shell: bash
      run: |
        if [ -e package-lock.json ]; then
          echo "package_manager=npm" >> $GITHUB_OUTPUT
          echo "install_cmd=npm ci" >> $GITHUB_OUTPUT
        elif [ -e yarn.lock ]; then
          echo "package_manager=yarn" >> $GITHUB_OUTPUT
          echo "install_cmd=yarn install --immutable" >> $GITHUB_OUTPUT
        elif [ -e pnpm-lock.yaml ]; then
          echo "package_manager=pnpm" >> $GITHUB_OUTPUT
          echo "install_cmd=pnpm install --frozen-lockfile" >> $GITHUB_OUTPUT
        fi

    - name: Install pnpm
      if: steps.detect.outputs.package_manager == 'pnpm'
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install Node dependencies
      if: steps.detect.outputs.package_manager
      uses: actions/setup-node@v3
      with:
        cache: ${{ steps.detect.outputs.package_manager }}

    - name: Install ${{ steps.detect.outputs.package_manager }} packages
      if: steps.detect.outputs.package_manager
      shell: bash
      run: ${{ steps.detect.outputs.install_cmd }}
