name: Trunk Check
author: trunk.io
description: The official trunk.io GitHub action

branding:
  icon: check
  color: green

inputs:
  client_payload:
    description: the client payload
    required: true

###
# current schema:
#
# version: string
# check_mode: string
# token: string
# repository: object
#   full_name: string
# upload_series: bool
###

runs:
  using: composite
  steps:
    - name: Checkout
      if: fromJSON(inputs.client_payload).version == '0.0.0'
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      with:
        repository: fromJSON(inputs.client_payload).repository.full_name

    - uses: ./../
      if: fromJSON(inputs.client_payload).version == '0.0.0'
      with:
        check-mode: fromJSON(inputs.client_payload).check_mode
        cache: true
        trunk-token: fromJSON(inputs.client_payload).token
        repo: fromJSON(inputs.client_payload).repository.full_name
        upload-series: fromJSON(inputs.client_payload).upload_series
