name: Trunk Check
author: trunk.io
description: The official trunk.io GitHub action

inputs:
  trunk-path:
    description: Path to Trunk Launcher
    required: false

  label:
    description: Label to append to the check run name
    required: false

runs:
  using: composite
  steps:
    - name: Locate trunk
      shell: bash
      run: |
        # Locate trunk
        ${GITHUB_ACTION_PATH}/locate_trunk.sh
      env:
        INPUTS_TRUNK_PATH: ${{ inputs.trunk-path }}

    - name: Run trunk check on pull request
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      shell: bash
      run: |
        # Run trunk check on pull request
        ${GITHUB_ACTION_PATH}/pull_request.sh
      env:
        GITHUB_EVENT_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_EVENT_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        INPUTS_LABEL: ${{ inputs.label }}

    - name: Run trunk check on all
      if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}
      shell: bash
      run: |
        # Run trunk check on all
        ${GITHUB_ACTION_PATH}/all.sh
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ github.token }}
        INPUTS_LABEL: ${{ inputs.label }}

    - name: Cleanup temporary files
      if: ${{ always() }}
      shell: bash
      run: |
        # Cleanup temporary files
        ${GITHUB_ACTION_PATH}/cleanup.sh
