name: Input setup
author: trunk.io
description: Sets up INPUT_ env vars and masks sensitive fields in the CheckService payload

inputs:
  use-payload:
    description: Whether or not the setup should use the payload
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: test
      shell: bash
      run: |
        pwd
        ls -la
        env
        NODE_DEBUG=cluster,net,http,fs,tls,module,timers node ${GITHUB_ACTION_PATH}/mask.js

# runs:
#   using: node16
#   main: /__w/dockertest/dockertest/.trunk-action/input-setup/mask.js
