name: Trunk Check
author: trunk.io
description: The official trunk.io GitHub action to install trunk

branding:
  icon: check
  color: green

runs:
  using: composite
  steps:
    - name: Locate trunk
      shell: bash
      run: ${GITHUB_ACTION_PATH}/locate_trunk.sh
