name: Trunk Check
on:
  workflow_call:
    inputs:
      client_payload:
        description: the client payload
        required: true
        type: string

###
# current schema:
#
# version: string
# check_mode: string
# token: string
# repository: object
#   full_name: string
# upload_series: bool
###

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: fromJSON(inputs.client_payload).version == '0.0.0'
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: ${{ fromJSON(inputs.client_payload).repository.full_name }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        if: fromJSON(inputs.client_payload).version == '0.0.0'
        with:
          check-mode: ${{ fromJSON(inputs.client_payload).check_mode }}
          cache: true
          trunk-token: ${{ fromJSON(inputs.client_payload).token }}
          repo: ${{ fromJSON(inputs.client_payload).repository.full_name }}
          upload-series: ${{ fromJSON(inputs.client_payload).upload_series }}
