name: Nightly
on:
  schedule:
    - cron: 0 8 * * 1-5
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Trunk Check
        uses: ./ # external users, use: trunk-io/trunk-action@v1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
