name: Nightly
on:
  schedule:
    - cron: 0 8 * * 1-5
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Trunk Check
        # external users, use: trunk-io/trunk-action@v1
        uses: ./
        with:
          check-mode: all
