name: Pull Request
on: [pull_request, workflow_dispatch]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Trunk Check
        # external users, use: trunk-io/trunk-action@v1
        uses: ./

  action_tests:
    name: Action tests
    uses: ./.github/workflows/action_tests.yaml

  repo_tests:
    name: Repository tests
    uses: ./.github/workflows/repo_tests.yaml

  docker_repo_tests:
    name: Repository tests (docker)
    uses: ./.github/workflows/docker_repo_tests.yaml
