name: repo_tests
on: [workflow_dispatch, workflow_call]

jobs:
  repo_test:
    name: trunk-action in ${{ matrix.repo }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        repo:
          - eslint/eslint
          - facebook/jest
          - jbeder/yaml-cpp
          - mochajs/mocha
          - pallets/flask
          - psf/black
          - replayio/devtools
          - square/leakcanary
          - terraform-linters/tflint
          - typescript-eslint/typescript-eslint
          - trunk-io/plugins
          - z-shell/wiki

    steps:
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          path: local-action

      - name: Run trunk-action in ${{ matrix.repo }}
        id: trunk
        uses: ./local-action/
        with:
          check-mode: all
        continue-on-error: true

      - name: Check for task failures
        if: always()
        shell: python
        run: |
          import json, sys

          landing_state = json.load(open('.trunk/landing_state.json'))
          failure_count = len(landing_state.get("taskFailures", []))

          if failure_count == 0:
            print("No task failures")
            sys.exit(0)

          if failure_count == 1:
            print(f'There was {failure_count} task failure')
          else:
            print(f'There were {failure_count} task failures')
          print('Failures can be viewed in the logs for the previous step')
          sys.exit(1)
