name: Tests
on: pull_request

jobs:
  only_reference_latest_release:
    name: Reference only the latest release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify
        run: |
          diff --color=always -u \
            <(git grep -ohP "(?<=trunk-io/trunk-action@)[\.\w-]+" | sort -u) \
            <(curl -s https://api.github.com/repos/trunk-io/trunk-action/releases/latest \
                | python3 -c "import json, sys; print(json.load(sys.stdin)['tag_name'])")
