name: repo_tests
on: [workflow_dispatch, workflow_call]

jobs:
  repo_test:
    name: trunk-action in ${{ matrix.repo }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        repo:
          - jbeder/yaml-cpp
          - replayio/devtools
          #- square/leakcanary
          #- terraform-linters/tflint
          - trunk-io/plugins
          - z-shell/wiki

    steps:
      - name: Checkout repo under test
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}

      - name: Checkout action
        uses: actions/checkout@v3
        with:
          path: local-action

      - name: Run trunk-action
        uses: ./local-action/
        with:
          check-mode: all

      - name: Check for linter/task failures
        if: always()
        shell: bash
        run: |
          if [ -n $(ls .trunk/out/) ]; then
            echo "Found linter/task failures"
            ls .trunk/out/
            exit 1
          fi
